### ISSUE TITLE
Segmentation faults

### ISSUE THREAD

**Issue by diegomontoya** [cshum/imagor#268]
Version: Imagor 1.3.2
Platform: Alpine Linux 3.17
Libvips: vips-8.13.3-r1
Libheif: libheif-1.14.0-r0
Golang: go-1.19.3-r0

Formats: Web + AVIF
Action: Resize Images

We are getting at least 1 segmentation fault per day when using imagor to resize images to webp/avif (50/50 ratio).

We are using the `app.ServeBlob` api from our golang program.

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x7fa28db8f2dd]

runtime stack:
runtime.throw({0x125a02b?, 0x7fa28fdd1c56?})
	/usr/lib/go/src/runtime/panic.go:1047 +0x5d fp=0x7fa252e35cb0 sp=0x7fa252e35c80 pc=0x46acbd
runtime.sigpanic()
	/usr/lib/go/src/runtime/signal_unix.go:819 +0x369 fp=0x7fa252e35d00 sp=0x7fa252e35cb0 pc=0x4815a9

goroutine 146318102 [syscall]:
runtime.cgocall(0xfffb70, 0xc2797c8000)
	/usr/lib/go/src/runtime/cgocall.go:158 +0x5c fp=0xc2797c7fd8 sp=0xc2797c7fa0 pc=0x436b1c
github.com/cshum/imagor/vips._Cfunc_thumbnail_image(0x22dee7eb840, 0xc034670ad8, 0x70, 0x70, 0x1, 0x0)
	_cgo_gotypes.go:1365 +0x4c fp=0xc2797c8000 sp=0xc2797c7fd8 pc=0xb0252c
github.com/cshum/imagor/vips.vipsThumbnail.func1(0x7fa28d0c71d8?, 0x4b635e?, 0x70, 0x70, 0x1, 0x0)
	/code-go/go/src/github.com/cshum/imagor/vips/vips.go:142 +0xa7 fp=0xc2797c8048 sp=0xc2797c8000 pc=0xb0b267
github.com/cshum/imagor/vips.vipsThumbnail(0x51aac5?, 0xc047f15a00?, 0xc179f02000?, 0x1d?, 0xc2797c8160?)
	/code-go/go/src/github.com/cshum/imagor/vips/vips.go:142 +0x65 fp=0xc2797c80b8 sp=0xc2797c8048 pc=0xb0b145
github.com/cshum/imagor/vips.(*Image).ThumbnailWithSize(0xc0d5537240, 0xc130412620?, 0xc047f15a00?, 0xc2797c8230?, 0xb059d7?)
	/code-go/go/src/github.com/cshum/imagor/vips/image.go:618 +0x25 fp=0xc2797c80f0 sp=0xc2797c80b8 pc=0xb077e5
github.com/cshum/imagor/vips.(*Processor).Thumbnail(0x22dee7eb840?, 0xc0d5537240?, 0x0?, 0xc2797c81b0?, 0x475611?, 0x0?)
	/code-go/go/src/github.com/cshum/imagor/vips/processor.go:271 +0xad fp=0xc2797c8150 sp=0xc2797c80f0 pc=0xafed4d
github.com/cshum/imagor/vips.(*Processor).process(_, {_, _}, _, {0x0, {0xc0588ca600, 0x3a}, {0x0, 0x0}, 0x1, ...}, ...)
	/code-go/go/src/github.com/cshum/imagor/vips/process.go:441 +0xeb3 fp=0xc2797c8418 sp=0xc2797c8150 pc=0xafb5f3
github.com/cshum/imagor/vips.(*Processor).Process(_, {_, _}, _, {0x0, {0xc0588ca600, 0x3a}, {0x0, 0x0}, 0x1, ...}, ...)
	/code-go/go/src/github.com/cshum/imagor/vips/process.go:278 +0xfc8 fp=0xc2797c88c0 sp=0xc2797c8418 pc=0xaf9028
github.com/cshum/imagor.(*Imagor).Do.func2({0x13cc688, 0xc051e62780}, 0x129a968)
	/code-go/go/src/github.com/cshum/imagor/imagor.go:362 +0x1149 fp=0xc2797c9270 sp=0xc2797c88c0 pc=0xaec009
github.com/cshum/imagor.(*Imagor).suppress(0x0?, {0x13cc688?, 0xc051e62780?}, {0x0?, 0x0?}, 0x1?)
	/code-go/go/src/github.com/cshum/imagor/imagor.go:571 +0x60f fp=0xc2797c9410 sp=0xc2797c9270 pc=0xaef04f
github.com/cshum/imagor.(*Imagor).Do(_, _, {0x0, {0x0, 0x0}, {0x0, 0x0}, 0x1, {0x0, 0x0}, ...})
```

**Comment by diegomontoya** [comment]
We added some internal comments to vips.go file so the above stacktrace line 142 actually points to `C.thumbnail_image` call below:

```
func vipsThumbnail(in *C.VipsImage, width, height int, crop Interesting, size Size) (*C.VipsImage, error) {
	var out *C.VipsImage

        if err := C.thumbnail_image(in, &out, C.int(width), C.int(height), C.int(crop), C.int(size)); err != 0 {
		return nil, handleImageError(out)
	}

	return out, nil
}
```

**Comment by diegomontoya** [comment]
Another fault variant. Other than comments added to vips.go, we did not make any functional changes to vips.go.

Line 121 of vips.go actually points to `C.clear_image(&ref)` :

```
func clearImage(ref *C.VipsImage) {
	C.clear_image(&ref)
}
```

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x7fd13a98f8d6]

runtime stack:
runtime.throw({0x125a02b?, 0x0?})
	/usr/lib/go/src/runtime/panic.go:1047 +0x5d fp=0x7fd105058658 sp=0x7fd105058628 pc=0x46acbd
runtime.sigpanic()
	/usr/lib/go/src/runtime/signal_unix.go:819 +0x369 fp=0x7fd1050586a8 sp=0x7fd105058658 pc=0x4815a9

goroutine 2706132 [syscall]:
runtime.cgocall(0xfff370, 0xc03cb9c308)
	/usr/lib/go/src/runtime/cgocall.go:158 +0x5c fp=0xc03cb9c2e0 sp=0xc03cb9c2a8 pc=0x436b1c
github.com/cshum/imagor/vips._Cfunc_clear_image(0xc046a6dd00)
	_cgo_gotypes.go:697 +0x45 fp=0xc03cb9c308 sp=0xc03cb9c2e0 pc=0xaff8c5
github.com/cshum/imagor/vips.clearImage.func1(0xc000536000?)
	/code-go/go/src/github.com/cshum/imagor/vips/vips.go:121 +0x45 fp=0xc03cb9c340 sp=0xc03cb9c308 pc=0xb0ae85
github.com/cshum/imagor/vips.clearImage(0x576341a67c0)
	/code-go/go/src/github.com/cshum/imagor/vips/vips.go:121 +0x5b fp=0xc03cb9c370 sp=0xc03cb9c340 pc=0xb0ae1b
github.com/cshum/imagor/vips.(*Image).Close(0xc034ced740)
	/code-go/go/src/github.com/cshum/imagor/vips/image.go:206 +0x65 fp=0xc03cb9c3c0 sp=0xc03cb9c370 pc=0xb05fe5
github.com/cshum/imagor/vips.(*Processor).Process.func3()
	/code-go/go/src/github.com/cshum/imagor/vips/process.go:207 +0x26 fp=0xc03cb9c3d8 sp=0xc03cb9c3c0 pc=0xafa6a6
runtime.deferreturn()
	/usr/lib/go/src/runtime/panic.go:476 +0x33 fp=0xc03cb9c418 sp=0xc03cb9c3d8 pc=0x469633
github.com/cshum/imagor/vips.(*Processor).Process(_, {_, _}, _, {0x0, {0xc046a6ec00, 0x38}, {0x0, 0x0}, 0x1, ...}, ...)
	/code-go/go/src/github.com/cshum/imagor/vips/process.go:322 +0x1614 fp=0xc03cb9c8c0 sp=0xc03cb9c418 pc=0xaf9674
github.com/cshum/imagor.(*Imagor).Do.func2({0x13cc688, 0xc03e217e00}, 0x129a968)
	/code-go/go/src/github.com/cshum/imagor/imagor.go:362 +0x1149 fp=0xc03cb9d270 sp=0xc03cb9c8c0 pc=0xaec009
github.com/cshum/imagor.(*Imagor).suppress(0x0?, {0x13cc688?, 0xc03e217e00?}, {0x0?, 0x0?}, 0x1?)
	/code-go/go/src/github.com/cshum/imagor/imagor.go:571 +0x60f fp=0xc03cb9d410 sp=0xc03cb9d270 pc=0xaef04f
github.com/cshum/imagor.(*Imagor).Do(_, _, {0x0, {0x0, 0x0}, {0x0, 0x0}, 0x1, {0x0, 0x0}, ...})
	/code-go/go/src/github.com/cshum/imagor/imagor.go:308 +0xcb9 fp=0xc03cb9d9f0 sp=0xc03cb9d410 pc=0xaea6b9
github.com/cshum/imagor.(*Imagor).Serve(_, {_, _}, {0x0, {0x0, 0x0}, {0x0, 0x0}, 0x1, {0x0, ...}, ...})
	/code-go/go/src/github.com/cshum/imagor/imagor.go:204 +0xc5 fp=0xc03cb9db18 sp=0xc03cb9d9f0 pc=0xae9805
github.com/cshum/imagor.(*Imagor).ServeBlob(_, {_, _}, _, {0x0, {0x0, 0x0}, {0x0, 0x0}, 0x1, ...})
	/code-go/go/src/github.com/cshum/imagor/imagor.go:217 +0xf3 fp=0xc03cb9dc58 sp=0xc03cb9db18 pc=0xae9953
```

**Comment by cshum** [comment]
Is this something coming off under high load, so it is not something that can be reproduced with a handful of images?

Would you try adding option 
```go
	imagor.New(
		...
		imagor.WithProcessConcurrency(int64(runtime.NumCPU()*2)),
		...
	)
```
to try limit process concurrency under num of CPUs * 2? See if it makes any difference.

**Comment by diegomontoya** [comment]
@cshum Process concurrency is already set at 1/2 of available cpu cores on the lxd container where 20 cores is assigned to the go program. So 10 cores is assigned to imagor processing out of 20. The cpu is not very much stressed so load is actually very low on average (around 3 load value). Memory usage of entire golang sever program during average load is around 65%.  So memory pressure doesn't appear to be a factor as well.

The the thing is, with the clearImage crash, your code actually check for null pointer before calling clearImage() which clears the C pointer. How is this crash possible?  We know that golang can/will switch process context at every function call, it is possible that between time the null check is checked and C.unref is actually called, golang has switched OS threads.

**Comment by cshum** [comment]
The crash comes from C segmentation fault (and hence the CGO bridge), which is some of the hardest bug to troubleshoot.

**Comment by diegomontoya** [comment]
> Golang may switch OS thread when spawning a new goroutine, depending on Go's internal scheduler. But for simply function call, it should be the same thread.

Golang scheduler does not guarantee that your next function call will be on same P thread. It's very different from even coroutines like Kotlin where you have have explicitly define suspend points. For golang, every method is implicit suspend-able. Also why we see some cgo init code use LockOSThread to avoid race conditions even when code is in same method call. 

As far as I know, a goroutine is assigned to a P process/thread. Many goroutines share the same P thread can be suspended at any moment at the point of a method call/exit, and be moved to another P process during the suspension.

**Comment by diegomontoya** [comment]
@cshum I see that Close is optional but I don't understand how it can be optional since C pointers are passed to Golang so go code must mange the de-ref. If Close is not called, wouldn't this leak r.image until libvips shutdown is called? I don't see any SetFinalizer called for the Image object that would auto call Close on object gc either. 

```
// Close manually closes the image and frees the memory. Calling Close() is optional.
// Images are automatically closed by GC. However, in high volume applications the GC
// can't keep up with the amount of memory, so you might want to manually close the images.
func (r *Image) Close() {
	r.lock.Lock()
	if r.image != nil {
		clearImage(r.image)
		r.image = nil
		log("vips", LogLevelDebug, fmt.Sprintf("closing image %p", r))
	}
	r.buf = nil
	r.lock.Unlock()
}
```

**Comment by cshum** [comment]
That's true about the Go's threading model, but libvips is generally thread safe except during startup. LockOSThread has quite some performance penalty, wouldn't want to deal with that on every image call unless there is no other way. 
If it is due to missing LockOSThread the error rate will go way higher than say, at least 1 times per day.

**Comment by cshum** [comment]
> @cshum I see that Close is optional but I don't understand how it can be optional since C pointers are passed to Golang so go code must mange the de-ref. If Close is not called, wouldn't this leak r.image until libvips shutdown is called? I don't see any SetFinalizer called for the Image object that would auto call Close on object gc either.
> 
> ```
> // Close manually closes the image and frees the memory. Calling Close() is optional.
> // Images are automatically closed by GC. However, in high volume applications the GC
> // can't keep up with the amount of memory, so you might want to manually close the images.
> func (r *Image) Close() {
> 	r.lock.Lock()
> 	if r.image != nil {
> 		clearImage(r.image)
> 		r.image = nil
> 		log("vips", LogLevelDebug, fmt.Sprintf("closing image %p", r))
> 	}
> 	r.buf = nil
> 	r.lock.Unlock()
> }
> ```

Image close is actually necessary as libvips/C doesn't do GC. It was previously rely on SetFinalizer but it was way more prone to SIGSEGV, as you can imagine Go GC is way more unpredictable. Now it only rely on manual defer call with a callback function stack.

Probably need to update some old documentations but let's do that after this issue.

**Comment by cshum** [comment]
@diegomontoya if we want to wrap LockOSThread around image creation and clear, then it should be called and deferred at the beginning of Process method. See if you want to test out this commit
https://github.com/cshum/imagor/pull/270/commits/a14d0fbaa693b6c6801e71e496ed0a1a1f4365db

**Comment by diegomontoya** [comment]
> @diegomontoya if we want to wrap LockOSThread around image creation and clear, then it should be called and deferred at the beginning of Process method. See if you want to test out this commit
> [a14d0fb](https://github.com/cshum/imagor/commit/a14d0fbaa693b6c6801e71e496ed0a1a1f4365db)

Pretty funny. We are already running this exact code on our nodes to test. We should get an answer in about 12-24 hours. The panic rate is about once per 12 hours.

**Comment by diegomontoya** [comment]
Unfortunately, even with LockOSThread at top of Process to guard against the entire vips operations switching threads, still seeing clearImage seg faults. Either vips image somewhere is returning duplicate images to golang causing double free or something else is happening. 

```
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x7f2db59378d6]

runtime stack:
runtime.throw({0x125a02b?, 0x1?})
	/usr/lib/go/src/runtime/panic.go:1047 +0x5d fp=0x7f2d772dd658 sp=0x7f2d772dd628 pc=0x46acbd
runtime.sigpanic()
	/usr/lib/go/src/runtime/signal_unix.go:819 +0x369 fp=0x7f2d772dd6a8 sp=0x7f2d772dd658 pc=0x48
15a9
```

**Comment by cshum** [comment]
Added disable one more config that can be related to some SIGSEGV cases on JPEG images

**Comment by diegomontoya** [comment]
@cshum Good news. It's been 8 hours and zero segfaults with latest libvips vector disabled. Too soon to say this is fixed but I am hopeful.  If fix is confirmed, maybe we can roll back on the LockOsThread protection.

**Comment by cshum** [comment]
@diegomontoya do let me know if it is keeping up. If it works I will tag a new release from that point.

I would not rollback LockOsThread right away though, as it still maybe part of the working formula I would not want mess it up lol. I may keep monitoring with or without LockOsThread for the next release.

**Comment by diegomontoya** [comment]
@cshum Zero segfaults! As far as I am concerned, current master branch has the issue confirmed fixed. =)

**Comment by cshum** [comment]
Available in v1.3.4 :)

@cocorossello you may also be interested as it may have fixed some the remaining segfaults errors.

**Comment by diegomontoya** [comment]
@cshum We have tested 1.3.4 with LockOsThread code disabled in Process and no segfaults over last 24 hours.

**Comment by cocorossello** [comment]
I deployed 1.3.4 yesterday, no segfaults as well since then!
